DROP TABLE IF EXISTS STUDENT;
CREATE TABLE STUDENT (
ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(50)
);

DROP TABLE IF EXISTS COURSE;
CREATE TABLE COURSE (
ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(50)
);

DROP TABLE IF EXISTS STUDENT_COURSE;
CREATE TABLE STUDENT_COURSE (
STUDENT_ID INT,
COURSE_ID INT,
PRIMARY KEY (STUDENT_ID, COURSE_ID)
)