--INSERT INTO STUDENT (ID, NAME) VALUES (1, 'RAJESH');
--INSERT INTO STUDENT (ID, NAME) VALUES (2, 'SIRISHA');

--INSERT INTO COURSE (ID, NAME) VALUES (1, 'JAVA')
--INSERT INTO COURSE (ID, NAME) VALUES (2, 'DOTNET')

--INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (1,1);
--INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (1,2);
--INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID) VALUES (2,2);